### ISSUE TITLE
;roll is broken

### ISSUE THREAD

**Issue by reticenti** [Roxxers/roxbot#13]
;roll 1d6
RoxBotBOT - Today at 8:12 PM
Expression missing. If you are unsure of what the format should be, please use ;help roll

;roll 2d20h1 + 7 (this is the example given in help file)
RoxBotBOT - Today at 8:12 PM
Expression missing. If you are unsure of what the format should be, please use ;help roll

**Comment by Roxxers** [comment]
Fixed in 3ff4302a7d9afef32b1692567c3869dedfea221d but one issue that still remains is trailing addition and subtraction isn't working. So I'll have to get @TBTerra on that.
