### ISSUE TITLE
Pride Command improper error output

### ISSUE THREAD

**Issue by jdude104** [Roxxers/roxbot#28]
The pride command, when given an invalid filter name, will simply echo back the first word it is given, instead of a full error message.  
![jeb](https://user-images.githubusercontent.com/1992616/49334381-c72e2f80-f5a2-11e8-9df9-285e1b472327.PNG)

**Comment by Roxxers** [comment]
Fixed in [v2.0.2](https://github.com/Roxxers/roxbot/releases/tag/v2.0.2)
