### ISSUE TITLE
Badtaglist breaks gelbooru search

### ISSUE THREAD

**Issue by jdude104** [Roxxers/roxbot#31]
In the [NSFW cog](https://github.com/Roxxers/roxbot/blob/master/roxbot/cogs/nsfw.py) the space is added after each tag instead of before, so searches get turned into **tag-badtag** instead of **tag -badtag** resulting in no results.

**Comment by Roxxers** [comment]
Fixed in [v2.0.2](https://github.com/Roxxers/roxbot/releases/tag/v2.0.2)
