### ISSUE TITLE
Embed type command capped at 256 characters in description only

### ISSUE THREAD

**Issue by jdude104** [Roxxers/roxbot#32]
In the new rich embed command type, the text for the description section is capped at 256 characters even though discord supports up to [2048 characters](https://discordapp.com/developers/docs/resources/channel#embed-limits). 
This same restriction is not placed on footer though, making the limit seemingly pointless.

**Comment by Roxxers** [comment]
Fixed in [v2.0.2](https://github.com/Roxxers/roxbot/releases/tag/v2.0.2). This now checks footer like it should do.
