### ISSUE TITLE
Spelling mistake in NSFW help output

### ISSUE THREAD

**Issue by jdude104** [Roxxers/roxbot#33]
Example 2 in the help command for the NSFW tag says **addbagtag** instead of **addbadtag**.  
![bagtaf](https://user-images.githubusercontent.com/1992616/49335555-4df00600-f5bd-11e8-9412-fad8f0c0c5ff.PNG)

**Comment by Roxxers** [comment]
Fixed in [v2.0.2](https://github.com/Roxxers/roxbot/releases/tag/v2.0.2)
