### ISSUE TITLE
add text to role command error for case-sensitivity reasons

### ISSUE THREAD

**Issue by SudosFTW** [Roxxers/roxbot#48]
add to the "role not found" text to make sure the role was typed correctly, as roles are case-sensitive. 
i.e.
`Role $role not found. Roles are case-sensitive, please make sure it was typed correctly.`

**Comment by Roxxers** [comment]
Closed in [v2.1.3](https://github.com/Roxxers/roxbot/releases/tag/v2.1.3) via commit 11d851bdbd3d7db9262ab93c7d149fc9b88d5b5a
