### ISSUE TITLE
Install fails on Debian Buster

### ISSUE THREAD

**Issue by Lynnesbian** [Roxxers/roxbot#50]
After following the guide, I couldn't install the requirements with `python3 -m pip install -r requirements.txt`. Here's the output: [roxbot-log.txt](https://github.com/Roxxers/roxbot/files/2974899/roxbot-log.txt)

I also found [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920900) in Debian's bug tracker.

**Comment by Roxxers** [comment]
This is a known bug. Remove dataset from the requirements.txt file. It's not even the orm I went with in the end so not only is it useless it kinda breaks installing this version of roxbot. Fixed in the next patch as well.
