### ISSUE TITLE
;deepfry on an unembedded image url gives an error 

### ISSUE THREAD

**Issue by reticenti** [Roxxers/roxbot#55]
Steps to reproduce
Get an image url
Run the command 
;deepfry \<https://foo.com/bar.jpg>

Roxbot gives an error

**Comment by reticenti** [comment]
Github auto format is messing up the command to run, but if you put the image url in discord unembed tags it doesn't work

**Comment by Roxxers** [comment]
Fixed in 1810345257f03044fe8a6f0de246df0d9f063cf2
