### ISSUE TITLE
Add demigender flags to ;pride

### ISSUE THREAD

**Issue by asynartesies** [Roxxers/roxbot#58]
particularly demiguy, demigirl, and deminonbinary.

**Comment by MxSummerNight** [comment]
Wanted to piggyback off this issue to request
polygender: https://www.deviantart.com/pride-flags/art/Polygender-1-543925900
and polysexual: https://en.m.wikipedia.org/wiki/Polysexuality#/media/File%3APolysexuality_Pride_Flag.svg

**Comment by Roxxers** [comment]
All flags have been added in a39970030803161e1185939390bdfc774562d103
